### ISSUE TITLE
No JFree Charts shown in Demo App

### ISSUE THREAD

**Issue by effad** [jfree/jfree-fxdemos#1]
Following your great presentation in Zürich, I wanted to try out the JFree Charts and thus cloned this project.
However, when I build it (mvn package) und then call:
   java -cp target/jfree-fxdemos-1.1-SNAPSHOT-jar-with-dependencies.jar -jar target/jfree-fxdemos-1.1-SNAPSHOT-jar-with-dependencies.jar
only the Orson charts will appear in the Demo application

**Comment by jfree** [comment]
There are 4 demo programs for JFreeChart in there.  However, in the pom.xml I'm setting the Orson Charts demo as the main class in the manifest, so that is the one that runs automatically.  To run the JFreeChart demos, use one of the following:

java -cp jfree-fxdemos-1.1-SNAPSHOT-jar-with-dependencies.jar org.jfree.chart.fx.demo.BarChartFXDemo1

java -cp jfree-fxdemos-1.1-SNAPSHOT-jar-with-dependencies.jar org.jfree.chart.fx.demo.CrosshairOverlayFXDemo1

java -cp jfree-fxdemos-1.1-SNAPSHOT-jar-with-dependencies.jar org.jfree.chart.fx.demo.PieChartFXDemo1

java -cp jfree-fxdemos-1.1-SNAPSHOT-jar-with-dependencies.jar org.jfree.chart.fx.demo.TimeSeriesChartFXDemo1

I hope you like the demos!
